teste flake8

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -42,9 +42,14 @@ jobs:
           branch: actions/black
 
     - name: Lint with flake8
+      id: action_flake8
       run: |
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
+        if [ $? -ne 0 ]; then
+          echo ":x: Flake8 found errors"
+          exit 1
+        fi
 
     - name: Check types with mypy
       run: mypy src
