black

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -31,16 +31,22 @@ jobs:
 
     - name: Create a pull request if there are any linting errors
       if: steps.action_black.outputs.is_formatted == 'true'
-      uses: peter-evans/create-pull-request@v3
-      with:
-        token: ${{ secrets.GITHUB_TOKEN }}
-        title: "Format Python code with psf/black push"
-        commit-message: ":art: Format Python code with psf/black"
-        body: |
-          There appear to be some python formatting errors in ${{ github.sha }}. This pull request
-          uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
-          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
-          branch: actions/black
+      run: |
+        echo "No linting errors found."
+        else:
+        run: |
+            echo "Linting errors found."
+            exit 1
+    #   uses: peter-evans/create-pull-request@v3
+    #   with:
+    #     token: ${{ secrets.GITHUB_TOKEN }}
+    #     title: "Format Python code with psf/black push"
+    #     commit-message: ":art: Format Python code with psf/black"
+    #     body: |
+    #       There appear to be some python formatting errors in ${{ github.sha }}. This pull request
+    #       uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
+    #       base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
+    #       branch: actions/black
 
     - name: flake8 Lint
       uses: suo/flake8-github-action@releases/v1
